name: Build and typecheck

on:
  workflow_call:

jobs:
  set-up:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Plugin Environment
        uses: ./.github/actions/setup-env

      - name: Typecheck
        run: yarn typecheck

      - name: Build plugin
        run: mkdir -p artifacts && yarn build --json=artifacts/currentBundleSize.json --no-devtool

      - name: Upload this build's bundle size artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: currentBundleSize
          path: ./artifacts/currentBundleSize.json
          overwrite: true
          retention-days: 90
