name: Generate main bundle size

on:
  workflow_call:

permissions:
  contents: read
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Setup Plugin Environment
        uses: ./.github/actions/setup-env

      - name: Make artifacts folder
        run: mkdir -p artifacts

      - name: Build frontend and generate bundle size
        run: yarn build --json=artifacts/mainBundleSize.json --no-devtool

      - name: Upload main bundle size artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: mainBundleSize
          path: ./artifacts/mainBundleSize.json
          overwrite: true
          retention-days: 90
